mylist = ["hihi" ,"haha" ,23 ,True ,34 ,11,"Bk" ]
print("mylist is :")
print(*mylist, sep = ", ")
newlist1 = mylist.append(0)
print("result after append newlist")
print(*mylist, sep = ", ")
newlist2 = mylist.insert(3, "tien")
print("result after insert ")
print(*mylist, sep = ", ")
list2 = ["banana" ,"apple" ,"lemon" , "melon"]
print("list2 is :")
print(*list2, sep = ", ")
newlist3 =mylist.extend(list2)
print("result after extend list2 in mylist")
print(*mylist, sep = ", ")
newlist4 = list2.index("apple")
print("position of apple in list2 is ")
print(newlist4)
mylist.remove("haha")
print("mylist after remove haha")
print(*list2, sep = ", ")
def myFunc (e):
	return len(e)
list2.sort(key=myFunc)
print("list2 after sort")
print(*list2)
list2.reverse()
print("list2 after reverse")
print(*list2)
list2.pop(1)
print("list2 after remove index(1)")
print(*list2)